# Generated by Django 4.0.4 on 2023-06-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('lanzamiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('cantidad_canciones', models.CharField(max_length=20)),
                ('tracklist', models.TextField(blank=True, null=True)),
                ('duracion', models.CharField(max_length=45)),
                ('notas', models.CharField(max_length=3)),
                ('disponibilidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(db_column='idArtista', primary_key=True, serialize=False)),
                ('album', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='album',
            name='id_artista',
            field=models.ForeignKey(db_column='idArtista', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='venta.artista'),
        ),
    ]
