# Generated by Django 4.0.4 on 2023-06-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_album_artista_delete_alumno_delete_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='id_artista',
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.AddField(
            model_name='album',
            name='id_genero',
            field=models.ForeignKey(db_column='idGenero', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='venta.genero'),
            preserve_default=False,
        ),
    ]
